### ISSUE TITLE
Multi Crew Support?

### ISSUE THREAD

**Issue by Alexalex1432** [X52EliteSetup/X52#1]
Currently if you're using the provided bindings (which btw, thanks a lot for), there isn't anything bound for multicrew buttons

**Comment by MichaelGreenNZ** [comment]
Hi Alex

Development on this stopped back around February last year. if you or someone you knows wants to take this and fork it off to update and make it compatible for MultiCrew and new versions of Elite, Please ask them to get in touch!

Cheers

Michael
